name: Link check

on:
  push:
    branches: [main]
    paths: ['**/*.md']
  schedule:
    - cron: '0 0 1 * *' # monthly

jobs:
  markdown-link-check:
    uses: janosh/workflows/.github/workflows/markdown-link-check.yml@main
